name: Python test

on:
  workflow_call:
    inputs:
      TEST_PATH:
        required: false
        type: string
        default: tests

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --group test
      - name: Test project
        run: uv run pytest ${{ inputs.TEST_PATH}}
