name: Example

on:
  workflow_call:
    inputs:
      MODULE_NAME:
        required: true
        type: string
      TEST_PATH:
        required: false
        type: string
        default: tests

jobs:
  lint-ruff:
    name: lint-ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --group dev

      - name: Lint project
        run: uv run ruff check ${{ inputs.MODULE_NAME}}

  lint-pylint:
    name: lint-pylint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --group dev

      - name: Add required deps
        run: uv add pylint-exit anybadge

      - name: Lint project
        run: uv run pylint --output-format=text ${{ inputs.MODULE_NAME}} | tee ./$PYTHON_LINT_DIRECTORY_NAME/pylint.log || uv run pylint-exit $?

      - name: Eval Lint
        run: |
          PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./$PYTHON_LINT_DIRECTORY_NAME/pylint.log)
          echo "Pylint score is $PYLINT_SCORE"


  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --group test

      - name: Test project
        run: uv run pytest ${{ inputs.TEST_PATH}}
