on:
  push:
    branches: [ "main", "develop" ]

permissions:
  id-token: write
  pages: write

jobs:
  lint:
    name: lint
    uses: unaisaralegui/workflow-templates/.github/workflows/python/lint.yml@main
    with:
      MODULE_NAME: test_mod

  test:
    name: test
    uses: unaisaralegui/workflow-templates/.github/workflows/python/test.yml@main
    with:
      TEST_PATH: tests

  build:
    name: build
    uses: unaisaralegui/workflow-templates/.github/workflows/python/build.yml@main
    needs:
      - lint
      - test

  pages:
    name: pages
    uses: unaisaralegui/workflow-templates/.github/workflows/python/pages.yml@main
    with:
      DOCS_PATH: docs
    needs:
      - build
