on:
  push:
    branches: [ "main", "develop" ]

jobs:
  lint:
    name: lint
    uses: ./.github/workflows/lint.yml
    with:
      MODULE_NAME: test_mod

  test:
    name: test
    uses: ./.github/workflows/test.yml
    with:
      TEST_PATH: tests

  build:
    name: build
    uses: ./.github/workflows/build.yml
    needs:
      - lint
      - test

  pages:
    name: pages
    uses: ./.github/workflows/pages.yml
    with:
      DOCS_PATH: docs
    needs:
      - build
