on:
  push:
    branches: [ "main", "develop" ]

jobs:
  lint:
    name: lint
    uses: ./.github/workflows/lint.yml
    with:
      MODULE_NAME: test_mod

  test:
    name: test
    uses: ./.github/workflows/test.yml
    with:
      TEST_PATH: tests

  build:
    name: build
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build project
        run: uv build --wheel
