name: CI - Lint, Test, Build, and Deploy Docs

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    uses: unaisaralegui/workflow-templates/.github/workflows/lint.yml@main
    with:
      MODULE_NAME: test_mod

  test:
    name: test
    uses: unaisaralegui/workflow-templates/.github/workflows/test.yml@main
    with:
      TEST_PATH: tests

  build:
    name: build
    uses: unaisaralegui/workflow-templates/.github/workflows/build.yml@main
    needs:
      - lint
      - test

  pages:
    name: pages
    uses: unaisaralegui/workflow-templates/.github/workflows/pages.yml@main
    with:
      DOCS_PATH: docs
    needs:
      - build
    permissions:
      id-token: write
      pages: write
