on:
  push:
    branches: [ "main", "develop" ]

jobs:
  lint:
    name: lint
    uses: ./.github/workflows/lint.yml
    with:
      MODULE_NAME: test_mod

  test:
    name: test
    uses: ./.github/workflows/test.yml
    with:
      TEST_PATH: tests