name: Python pages

on:
  workflow_call:
    inputs:
      DOCS_PATH:
        required: false
        type: string
        default: docs

jobs:
  pages:
    name: pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the deps
        run: pip install sphinx sphinx_rtd_theme myst_parser

      - name: Run pages
        run: sphinx-build -b html ${{ inputs.DOCS_PATH}} _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
