name: Example

on:
  push:
    branches: [ "main" ]


jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-groups --all-extras

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Lint project
        run: uv run ruff
