name: Example

on:
  push:
    branches: [ "main" ]

env:
  MODULE_NAME: test_mod
  TEST_PATH: tests

jobs:
  lint-ruff:
    name: lint-ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --group dev

      - name: Lint project
        run: uv run ruff check $MODULE_NAME

  lint-pylint:
    name: lint-pylint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --group dev

      - name: Lint project
        run: uv run pylint $MODULE_NAME

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --group test

      - name: Test project
        run: uv run pytest $TEST_PATH

  build:
    name: build
    runs-on: ubuntu-latest
    needs:
      - lint-ruff
      - lint-pylint
      - test
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build project
        run: uv build --wheel

  deploy:
    name: build
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: List files
        run: ls dist
